# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Maxwell Martins Dalboni
title: Senior Software Developer
email: dalboni.max@hotmail.com
website: www.github.com/mdalboni

# Social links
#twitter_username: maxdalboni
github_username:  mdalboni
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: maxdalboni
linkedin_username: maxwell-dalboni-598670103
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there fellow, my name's Maxwell and I'm a software developer. I am graduated in Control and Automation Engineering, working with computers and softwares since 2007.
  I am a problem solver and a bug finder, experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.
  At the moment trying to learn more about Data Science.

  I am most skilled in: <mark>Python</mark>, <mark>PySide2/PyQt5</mark> and <mark>IoT</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
